name: Build AIX
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4

      - name: Setup Java
        uses: actions/setup-java@v4 # Updated to v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Rush
        run: |
          curl -fsSL https://raw.githubusercontent.com/shreyashsaitwal/rush-cli/main/scripts/install/install.sh | bash
          /home/runner/.rush/bin/rush build

      - name: Upload Result
        uses: actions/upload-artifact@v4 # This was the error, fixed to v4
        with:
          name: MyExtensionFile
          path: "out/*.aix"
          
